export const GPT_PROVIDERS = {
  enjoyai: {
    key: "enjoyai",
    name: "EnjoyAI",
    models: [
      "gpt-4o-mini",
      "gpt-4o",
      "chatgpt-4o-latest",
      "gpt-4-turbo",
      "gpt-4",
      "anthropic/claude-3.5-sonnet",
      "anthropic/claude-3.5-haiku",
      "meta-llama/llama-3.3-70b-instruct",
      "google/gemini-2.0-flash-exp",
      "google/gemini-pro-1.5",
      "google/gemini-flash-1.5",
      "perplexity/llama-3.1-sonar-huge-128k-online",
      "perplexity/llama-3.1-sonar-large-128k-online",
      "deepseek/deepseek-chat",
      "deepseek/deepseek-coder",
    ],
    configurable: [
      "model",
      "roleDefinition",
      "temperature",
      "numberOfChoices",
      "maxTokens",
      "frequencyPenalty",
      "presencePenalty",
      "historyBufferSize",
      "tts",
    ],
  },
  openai: {
    key: "openai",
    name: "OpenAI",
    models: [
      "gpt-4o-mini",
      "gpt-4o",
      "chatgpt-4o-latest",
      "gpt-4-turbo",
      "gpt-4",
      "gpt-3.5-turbo",
    ],
    configurable: [
      "model",
      "baseUrl",
      "roleDefinition",
      "temperature",
      "numberOfChoices",
      "maxTokens",
      "frequencyPenalty",
      "presencePenalty",
      "historyBufferSize",
      "tts",
    ],
  },
};
