export const TTS_PROVIDERS = {
  enjoyai: {
    name: "EnjoyAI",
    models: ["openai/tts-1", "openai/tts-1-hd", "azure/speech"],
    voices: [
      {
        label: "Alloy",
        value: "alloy",
        provider: "openai",
      },
      {
        label: "Echo",
        value: "echo",
        provider: "openai",
      },
      {
        label: "Fable",
        value: "fable",
        provider: "openai",
      },
      {
        label: "Onyx",
        value: "onyx",
        provider: "openai",
      },
      {
        label: "Nova",
        value: "nova",
        provider: "openai",
      },
      {
        label: "Shimmer",
        value: "shimmer",
        provider: "openai",
      },
      {
        label: "Katja (Female)",
        value: "de-DE-KatjaNeural",
        language: "de-DE",
        provider: "azure",
      },
      {
        label: "Conradl (Male)",
        value: "de-DE-ConradNeural",
        language: "de-DE",
        provider: "azure",
      },
      {
        label: "Amala (Female)",
        value: "de-DE-AmalaNeural",
        language: "de-DE",
        provider: "azure",
      },
      {
        label: "Bernd (Male)",
        value: "de-DE-BerndNeural",
        language: "de-DE",
        provider: "azure",
      },
      {
        label: "Christoph (Male)",
        value: "de-DE-ChristophNeural",
        language: "de-DE",
        provider: "azure",
      },
      {
        label: "Elke (Female)",
        value: "de-DE-ElkeNeural",
        language: "de-DE",
        provider: "azure",
      },
      {
        label: "Gisela (Female, Child)",
        value: "de-DE-GiselaNeural",
        language: "de-DE",
        provider: "azure",
      },
      {
        label: "Kasper (Male)",
        value: "de-DE-KasperNeural",
        language: "de-DE",
        provider: "azure",
      },
      {
        label: "Killian (Male)",
        value: "de-DE-KillianNeural",
        language: "de-DE",
        provider: "azure",
      },
      {
        label: "Klarissa (Female)",
        value: "de-DE-KlarissaNeural",
        language: "de-DE",
        provider: "azure",
      },
      {
        label: "Klaus (Male)",
        value: "de-DE-KlausNeural",
        language: "de-DE",
        provider: "azure",
      },
      {
        label: "Louisa (Female)",
        value: "de-DE-LouisaNeural",
        language: "de-DE",
        provider: "azure",
      },
      {
        label: "Maja (Female)",
        value: "de-DE-MajaNeural",
        language: "de-DE",
        provider: "azure",
      },
      {
        label: "Ralf (Male)",
        value: "de-DE-RalfNeural",
        language: "de-DE",
        provider: "azure",
      },
      {
        label: "Tanja (Female)",
        value: "de-DE-TanjaNeural",
        language: "de-DE",
        provider: "azure",
      },
      {
        label: "Sonia (Female)",
        value: "en-GB-SoniaNeural",
        language: "en-GB",
        provider: "azure",
      },
      {
        label: "Ryan (Male)",
        value: "en-GB-RyanNeural",
        language: "en-GB",
        provider: "azure",
      },
      {
        label: "Libby (Female)",
        value: "en-GB-LibbyNeural",
        language: "en-GB",
        provider: "azure",
      },
      {
        label: "Abbi (Female)",
        value: "en-GB-AbbiNeural",
        language: "en-GB",
        provider: "azure",
      },
      {
        label: "Alfie (Male)",
        value: "en-GB-AlfieNeural",
        language: "en-GB",
        provider: "azure",
      },
      {
        label: "Bella (Female)",
        value: "en-GB-BellaNeural",
        language: "en-GB",
        provider: "azure",
      },
      {
        label: "Elliot (Male)",
        value: "en-GB-ElliotNeural",
        language: "en-GB",
        provider: "azure",
      },
      {
        label: "Ethan (Male)",
        value: "en-GB-EthanNeural",
        language: "en-GB",
        provider: "azure",
      },
      {
        label: "Hollie (Female)",
        value: "en-GB-HollieNeural",
        language: "en-GB",
        provider: "azure",
      },
      {
        label: "Maisie (Female, Child)",
        value: "en-GB-MaisieNeural",
        language: "en-GB",
        provider: "azure",
      },
      {
        label: "Noah (Male)",
        value: "en-GB-NoahNeural",
        language: "en-GB",
        provider: "azure",
      },
      {
        label: "Oliver (Male)",
        value: "en-GB-OliverNeural",
        language: "en-GB",
        provider: "azure",
      },
      {
        label: "Olivia (Female)",
        value: "en-GB-OliviaNeural",
        language: "en-GB",
        provider: "azure",
      },
      {
        label: "Thomas (Male)",
        value: "en-GB-ThomasNeural",
        language: "en-GB",
        provider: "azure",
      },
      {
        label: "Ava (Female)",
        value: "en-US-AvaNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Andrew (Male)",
        value: "en-US-AndrewNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Emma (Female)",
        value: "en-US-EmmaNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Brian (Male)",
        value: "en-US-BrianNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Jenny (Female)",
        value: "en-US-JennyNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Guy (Male)",
        value: "en-US-GuyNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Aria (Female)",
        value: "en-US-AriaNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Davis (Male)",
        value: "en-US-DavisNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Jane (Female)",
        value: "en-US-JaneNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Jason (Male)",
        value: "en-US-JasonNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Sara (Female)",
        value: "en-US-SaraNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Tony (Male)",
        value: "en-US-TonyNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Nancy (Female)",
        value: "en-US-NancyNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Amber (Female)",
        value: "en-US-AmberNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Ana (Female, Child)",
        value: "en-US-AnaNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Ashley (Female)",
        value: "en-US-AshleyNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Brandon (Male)",
        value: "en-US-BrandonNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Christopher (Male)",
        value: "en-US-ChristopherNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Cora (Female)",
        value: "en-US-CoraNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Elizabeth (Female)",
        value: "en-US-ElizabethNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Eric (Male)",
        value: "en-US-EricNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Jacob (Male)",
        value: "en-US-JacobNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Michelle (Female)",
        value: "en-US-MichelleNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Monica (Female)",
        value: "en-US-MonicaNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Roger (Male)",
        value: "en-US-RogerNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Steffan (Male)",
        value: "en-US-SteffanNeural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "AIGenerate1 (Male)",
        value: "en-US-AIGenerate1Neural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "AIGenerate2 (Female)",
        value: "en-US-AIGenerate2Neural",
        language: "en-US",
        provider: "azure",
      },
      {
        label: "Elvira (Female)",
        value: "es-ES-ElviraNeural",
        language: "es-ES",
        provider: "azure",
      },
      {
        label: "Alvaro (Male)",
        value: "es-ES-AlvaroNeural",
        language: "es-ES",
        provider: "azure",
      },
      {
        label: "Abril (Female)",
        value: "es-ES-AbrilNeural",
        language: "es-ES",
        provider: "azure",
      },
      {
        label: "Arnau (Male)",
        value: "es-ES-ArnauNeural",
        language: "es-ES",
        provider: "azure",
      },
      {
        label: "Dario (Male)",
        value: "es-ES-DarioNeural",
        language: "es-ES",
        provider: "azure",
      },
      {
        label: "Elias (Male)",
        value: "es-ES-EliasNeural",
        language: "es-ES",
        provider: "azure",
      },
      {
        label: "Estrella (Female)",
        value: "es-ES-EstrellaNeural",
        language: "es-ES",
        provider: "azure",
      },
      {
        label: "Irene (Female)",
        value: "es-ES-IreneNeural",
        language: "es-ES",
        provider: "azure",
      },
      {
        label: "Laia (Female)",
        value: "es-ES-LaiaNeural",
        language: "es-ES",
        provider: "azure",
      },
      {
        label: "Lia (Female)",
        value: "es-ES-LiaNeural",
        language: "es-ES",
        provider: "azure",
      },
      {
        label: "Nil (Male)",
        value: "es-ES-NilNeural",
        language: "es-ES",
        provider: "azure",
      },
      {
        label: "Saul (Male)",
        value: "es-ES-SaulNeural",
        language: "es-ES",
        provider: "azure",
      },
      {
        label: "Teo (Male)",
        value: "es-ES-TeoNeural",
        language: "es-ES",
        provider: "azure",
      },
      {
        label: "Triana (Female)",
        value: "es-ES-TrianaNeural",
        language: "es-ES",
        provider: "azure",
      },
      {
        label: "Vera (Female)",
        value: "es-ES-VeraNeural",
        language: "es-ES",
        provider: "azure",
      },
      {
        label: "Ximena (Female)",
        value: "es-ES-XimenaNeural",
        language: "es-ES",
        provider: "azure",
      },
      {
        label: "Denise (Female)",
        value: "fr-FR-DeniseNeural",
        language: "fr-FR",
        provider: "azure",
      },
      {
        label: "Henri (Male)",
        value: "fr-FR-HenriNeural",
        language: "fr-FR",
        provider: "azure",
      },
      {
        label: "Alain (Male)",
        value: "fr-FR-AlainNeural",
        language: "fr-FR",
        provider: "azure",
      },
      {
        label: "Brigitte (Female)",
        value: "fr-FR-BrigitteNeural",
        language: "fr-FR",
        provider: "azure",
      },
      {
        label: "Celeste (Female)",
        value: "fr-FR-CelesteNeural",
        language: "fr-FR",
        provider: "azure",
      },
      {
        label: "Claude (Male)",
        value: "fr-FR-ClaudeNeural",
        language: "fr-FR",
        provider: "azure",
      },
      {
        label: "Coralie (Female)",
        value: "fr-FR-CoralieNeural",
        language: "fr-FR",
        provider: "azure",
      },
      {
        label: "Eloise (Female, Child)",
        value: "fr-FR-EloiseNeural",
        language: "fr-FR",
        provider: "azure",
      },
      {
        label: "Jacqueline (Female)",
        value: "fr-FR-JacquelineNeural",
        language: "fr-FR",
        provider: "azure",
      },
      {
        label: "Jerome (Male)",
        value: "fr-FR-JeromeNeural",
        language: "fr-FR",
        provider: "azure",
      },
      {
        label: "Josephine (Female)",
        value: "fr-FR-JosephineNeural",
        language: "fr-FR",
        provider: "azure",
      },
      {
        label: "Maurice (Male)",
        value: "fr-FR-MauriceNeural",
        language: "fr-FR",
        provider: "azure",
      },
      {
        label: "Yves (Male)",
        value: "fr-FR-YvesNeural",
        language: "fr-FR",
        provider: "azure",
      },
      {
        label: "Yvette (Female)",
        value: "fr-FR-YvetteNeural",
        language: "fr-FR",
        provider: "azure",
      },
      {
        label: "Elsa (Female)",
        value: "it-IT-ElsaNeural",
        language: "it-IT",
        provider: "azure",
      },
      {
        label: "Isabella (Female)",
        value: "it-IT-IsabellaNeural",
        language: "it-IT",
        provider: "azure",
      },
      {
        label: "Diego (Male)",
        value: "it-IT-DiegoNeural",
        language: "it-IT",
        provider: "azure",
      },
      {
        label: "Benigno (Male)",
        value: "it-IT-BenignoNeural",
        language: "it-IT",
        provider: "azure",
      },
      {
        label: "Calimero (Male)",
        value: "it-IT-CalimeroNeural",
        language: "it-IT",
        provider: "azure",
      },
      {
        label: "Cataldo (Male)",
        value: "it-IT-CataldoNeural",
        language: "it-IT",
        provider: "azure",
      },
      {
        label: "Fabiola (Female)",
        value: "it-IT-FabiolaNeural",
        language: "it-IT",
        provider: "azure",
      },
      {
        label: "Fiamma (Female)",
        value: "it-IT-FiammaNeural",
        language: "it-IT",
        provider: "azure",
      },
      {
        label: "Gianni (Male)",
        value: "it-IT-GianniNeural",
        language: "it-IT",
        provider: "azure",
      },
      {
        label: "Imelda (Female)",
        value: "it-IT-ImeldaNeural",
        language: "it-IT",
        provider: "azure",
      },
      {
        label: "Irma (Female)",
        value: "it-IT-IrmaNeural",
        language: "it-IT",
        provider: "azure",
      },
      {
        label: "Lisandro (Male)",
        value: "it-IT-LisandroNeural",
        language: "it-IT",
        provider: "azure",
      },
      {
        label: "Palmira (Female)",
        value: "it-IT-PalmiraNeural",
        language: "it-IT",
        provider: "azure",
      },
      {
        label: "Pierina (Female)",
        value: "it-IT-PierinaNeural",
        language: "it-IT",
        provider: "azure",
      },
      {
        label: "Rinaldo (Male)",
        value: "it-IT-RinaldoNeural",
        language: "it-IT",
        provider: "azure",
      },
      {
        label: "Giuseppe (Male)",
        value: "it-IT-GiuseppeNeural",
        language: "it-IT",
        provider: "azure",
      },
      {
        label: "NanamiNeural (Female)",
        value: "ja-JP-NanamiNeural",
        language: "ja-JP",
        provider: "azure",
      },
      {
        label: "KeitaNeural (Male)",
        value: "ja-JP-KeitaNeural",
        language: "ja-JP",
        provider: "azure",
      },
      {
        label: "AoiNeural (Female)",
        value: "ja-JP-AoiNeural",
        language: "ja-JP",
        provider: "azure",
      },
      {
        label: "DaichiNeural (Male)",
        value: "ja-JP-DaichiNeural",
        language: "ja-JP",
        provider: "azure",
      },
      {
        label: "MayuNeural (Female)",
        value: "ja-JP-MayuNeural",
        language: "ja-JP",
        provider: "azure",
      },
      {
        label: "NaokiNeural (Male)",
        value: "ja-JP-NaokiNeural",
        language: "ja-JP",
        provider: "azure",
      },
      {
        label: "ShioriNeural (Female)",
        value: "ja-JP-ShioriNeural",
        language: "ja-JP",
        provider: "azure",
      },
      {
        label: "SunHi (Female)",
        value: "ko-KR-SunHiNeural",
        language: "ko-KR",
        provider: "azure",
      },
      {
        label: "InJoon (Male)",
        value: "ko-KR-InJoonNeural",
        language: "ko-KR",
        provider: "azure",
      },
      {
        label: "BongJin (Male)",
        value: "ko-KR-BongJinNeural",
        language: "ko-KR",
        provider: "azure",
      },
      {
        label: "GookMin (Male)",
        value: "ko-KR-GookMinNeural",
        language: "ko-KR",
        provider: "azure",
      },
      {
        label: "JiMin (Female)",
        value: "ko-KR-JiMinNeural",
        language: "ko-KR",
        provider: "azure",
      },
      {
        label: "SeoHyeon (Female)",
        value: "ko-KR-SeoHyeonNeural",
        language: "ko-KR",
        provider: "azure",
      },
      {
        label: "SoonBok (Female)",
        value: "ko-KR-SoonBokNeural",
        language: "ko-KR",
        provider: "azure",
      },
      {
        label: "YuJin (Female)",
        value: "ko-KR-YuJinNeural",
        language: "ko-KR",
        provider: "azure",
      },
      {
        label: "Hyunsu (Male)",
        value: "ko-KR-HyunsuNeural1",
        language: "ko-KR",
        provider: "azure",
      },
      {
        label: "Xiaoxiao (Female)",
        value: "zh-CN-XiaoxiaoNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "Yunxi (Male)",
        value: "zh-CN-YunxiNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "Yunjian (Male)",
        value: "zh-CN-YunjianNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "Xiaoyi (Female)",
        value: "zh-CN-XiaoyiNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "Yunyang (Male)",
        value: "zh-CN-YunyangNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "Xiaochen (Female)",
        value: "zh-CN-XiaochenNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "Xiaohan (Female)",
        value: "zh-CN-XiaohanNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "Xiaomeng (Female)",
        value: "zh-CN-XiaomengNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "Xiaomo (Female)",
        value: "zh-CN-XiaomoNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "Xiaoqiu (Female)",
        value: "zh-CN-XiaoqiuNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "Xiaorui (Female)",
        value: "zh-CN-XiaoruiNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "Xiaoshuang (Female, Child)",
        value: "zh-CN-XiaoshuangNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "Xiaoyan (Female)",
        value: "zh-CN-XiaoyanNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "Xiaoyou (Female, Child)",
        value: "zh-CN-XiaoyouNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "Xiaozhen (Female)",
        value: "zh-CN-XiaozhenNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "Yunfeng (Male)",
        value: "zh-CN-YunfengNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "Yunhao (Male)",
        value: "zh-CN-YunhaoNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "Yunxia (Male)",
        value: "zh-CN-YunxiaNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "Yunye (Male)",
        value: "zh-CN-YunyeNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "Yunze (Male)",
        value: "zh-CN-YunzeNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "Xiaorou (Female)",
        value: "zh-CN-XiaorouNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "XiaoxiaoDialects (Female)",
        value: "zh-CN-XiaoxiaoDialectsNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "Yunjie (Male)",
        value: "zh-CN-YunjieNeural",
        language: "zh-CN",
        provider: "azure",
      },
      {
        label: "HiuMaan (Female)",
        value: "zh-HK-HiuMaanNeural",
        language: "zh-HK",
        provider: "azure",
      },
      {
        label: "WanLung (Male)",
        value: "zh-HK-WanLungNeural",
        language: "zh-HK",
        provider: "azure",
      },
      {
        label: "HiuGaai (Female)",
        value: "zh-HK-HiuGaaiNeural",
        language: "zh-HK",
        provider: "azure",
      },
      {
        label: "Premwadee (Female)",
        value: "th-TH-PremwadeeNeural",
        language: "th-TH",
        provider: "azure",
      },
      {
        label: "Niwat (Male)",
        value: "th-TH-NiwatNeural",
        language: "th-TH",
        provider: "azure",
      },
      {
        label: "Achara (Male)",
        value: "th-TH-AcharaNeural",
        language: "th-TH",
        provider: "azure",
      },
      {
        label: "An (Female)",
        value: "vi-VN-HoaiMyNeural",
        language: "vi-VN",
        provider: "azure",
      },
      {
        label: "Hoai (Male)",
        value: "vi-VN-NamMinhNeural",
        language: "vi-VN",
        provider: "azure",
      },
      {
        label: "Giang (Female)",
        value: "vi-VN-NgocHoaiGiangNeural",
        language: "vi-VN",
        provider: "azure",
      },
      {
        label: "Linh (Female)",
        value: "vi-VN-ThanhLinhNeural",
        language: "vi-VN",
        provider: "azure",
      },
      {
        label: "Mai (Female)",
        value: "vi-VN-HuuMaiNeural",
        language: "vi-VN",
        provider: "azure",
      },
      {
        label: "Nam (Male)",
        value: "vi-VN-HoaiNamNeural",
        language: "vi-VN",
        provider: "azure",
      },
    ],
    configurable: ["model", "language", "voice"],
  },
  openai: {
    name: "OpenAI",
    models: ["tts-1", "tts-1-hd"],
    voices: [
      {
        label: "Alloy",
        value: "alloy",
        provider: "openai",
      },
      {
        label: "Echo",
        value: "echo",
        provider: "openai",
      },
      {
        label: "Fable",
        value: "fable",
        provider: "openai",
      },
      {
        label: "Onyx",
        value: "onyx",
        provider: "openai",
      },
      {
        label: "Nova",
        value: "nova",
        provider: "openai",
      },
      {
        label: "Shimmer",
        value: "shimmer",
        provider: "openai",
      },
    ],
    configurable: ["model", "language", "voice", "baseUrl"],
  },
};
